/*
 * action类型 
 */
export const GET_TOTAL_AMOUNT = "GET_TOTAL_AMOUNT"; /* 获取总金额 */
export const GET_LATELY_LIST = "GET_LATELY_LIST"; /* 获取最近订单列表 */

export const GET_TOTAL_AMOUNT_REQUEST = "GET_TOTAL_AMOUNT_REQUEST";
export const GET_TOTAL_AMOUNT_FAILURE = "GET_TOTAL_AMOUNT_FAILURE";
export const GET_TOTAL_AMOUNT_SUCCESS = "GET_TOTAL_AMOUNT_SUCCESS";

export const GET_LATELY_LIST_REQUEST = "GET_LATELY_LIST_REQUEST";
export const GET_LATELY_LIST_FAILURE = "GET_LATELY_LIST_FAILURE";
export const GET_LATELY_LIST_SUCCESS = "GET_LATELY_LIST_SUCCESS";